### PR TITLE
Dockerize development

### PR DESCRIPTION
**Pull request by Jwashton**
This PR provides the configuration changes needed to run Elixir and Phoenix inside a containerized dev environment, without requiring official "devcontainer" support.

To start the project:

```bash
docker compose up -d
```

To enter the development container:

```bash
docker compose exec --user developer app bash
```

From there you should have a prompt where you can run `mix setup`, or any other command needed.

While we expect that most file editing/version control would happen outside the container, the image does provide tools for `git`, `curl` (download a file), `gpg` (sign your commits) and `rg` (faster than `ack` or `ag`), and `vim`. Others can be installed in future as needed.

### CODE REVIEW

**Comment by Jwashton** [comment]
I can confirm this configuration works with the following setups:

* Raw `docker` on a Linux machine
* A VSCode devcontainer on a Linux machine
* A GitHub Codespace on a Linux machine

It would be helpful to know if this works or not on Windows.

I haven't been able to get it to work with Podman, due to user namespace issues. I'd like to think those should be solvable, but they might not be solvable with the `su-exec` approach in the entrypoint.

I do observe that this has broken the CI configuration, specifically the host to reach the DB is now incorrect. We'll need to fix that before this can be accepted.

**Comment by ericridgeway** [comment]
Running `docker compose up -d` added a new line on the container page. Before under the "InkFlier" container we had db and adminer. I now also see "app"!
(Are these also called "containers"? "sub-containers" under the inkflier folder/container?)

I can even click the new "app"'s *image* and see "erlang 27 & elixir 1.17"

Plus "alpine", which docker says is a lightweight linux.
- So if I understand right, that's the little virtual computer that's running our elixir
- And we're trying to remote-desktop from our windows computer to that one  (Even tho yes, technically, they're on the same physical computer)

  - And there's some struggle as to which of those two computers all the actual .ex files are stored on (the virtual linux one) vs where our IDE/vim is (the windows one) ?

**Comment by ericridgeway** [comment]
Very cool that I can get that far, and viewing it in the nice docker desktop makes things slightly less scary/new/confusing :)

First possible problem:
- running things on the windows-computer -only side, I can't connect to the db anymore. Running "mix test" in my usual console window complains

Does [this](https://github.com/Jwashton/ink-flier/pull/24/files#diff-3493e6b5ddf34891e572f911db893efd9e46af828e011ea778a7c1eb64763588L9) need to be removed from the compose file for the new stuff to work?
- Maybe it doesn't matter since the goal is to be not running mix test (or even having an elixir install at all) from the windows-computer

**Comment by ericridgeway** [comment]
Can't get as far as the 2nd command with bash. Looks like the "app" container can't start. "exec /home/developer/entrypoint.sh: no such file or directory"

I see a new "/scripts/entrypoint.sh" in this branch, but haven't yet tracked down which file's trying to point at that, or why it's trying to use the full linux'y path instead of the relative-to-current-directory or relative-to-docker-compose path, or something

**Comment by ericridgeway** [comment]
Assuming I get as far as running the bash command, that'll be like having a prompt on the windows computer that runs commands on the linux computer?

Running the `vim` command you mentioned would probably run the terminal vim right in that prompt?

And some of the ssh neovim stuff you were asking about was so I could potentially connect my windows vim through that terminal/port/whatever and edit files on the virtual linux computer?

**Comment by Jwashton** [comment]
> And there's some struggle as to which of those two computers all the actual .ex files are stored on (the virtual linux one) vs where our IDE/vim is (the windows one) ?

Not so much where they are, more a question of who owns them. File ownership works a bit differently between Windows and Linux, so trying to make everybody agree is the trick.

> Does [this](https://github.com/Jwashton/ink-flier/pull/24/files#diff-3493e6b5ddf34891e572f911db893efd9e46af828e011ea778a7c1eb64763588L9) need to be removed from the compose file for the new stuff to work?

Fair question. We can totally restore that port binding. Some people like to have around for debugging purposes anyways. I'll push a commit restoring that configuration. 👍 

> Can't get as far as the 2nd command with bash. Looks like the "app" container can't start. "exec /home/developer/entrypoint.sh: no such file or directory"

Well, ah, that's not good.

> Assuming I get as far as running the bash command, that'll be like having a prompt on the windows computer that runs commands on the linux computer?

Sort of, yes. 👍 

> Running the vim command you mentioned would probably run the terminal vim right in that prompt?

Yes. Useful on occasion, but probably not what you normally want.

> And some of the ssh neovim stuff you were asking about was so I could potentially connect my windows vim through that terminal/port/whatever and edit files on the virtual linux computer?

All the SSH stuff I was asking about was me wondering whether some sort of remote development set up (like a Digital Ocean droplet or a GitHub Codespaces workspace) would be a reasonable approach. That's not relevant to the approach attempted in this MR.

**Pull request merged**
